### ISSUE TITLE
What do you mean by add this?

### ISSUE THREAD

**Issue by Wjplatformer** [2KAbhishek/Posh2K#1]
![image](https://user-images.githubusercontent.com/82447031/205492245-501a7946-3cc2-4440-9238-490bc84f7a4f.png)
I assume you don't run this. But where do you add this thing? 😁😊😅😶‍🌫️

**Comment by 2KAbhishek** [comment]
Please check cmd/clink config files

**Comment by Wjplatformer** [comment]
ah, I think I didn't dig deep enough into Google. Alright then

**Comment by Wjplatformer** [comment]
Sir, I think I ended up not using cmd because it was too troublesome. Thank you!
![image](https://user-images.githubusercontent.com/82447031/205785299-8024eb2a-6bd8-430e-9774-37b11ade059d.png)
