### ISSUE TITLE
[BUG]: Wait a second

### ISSUE THREAD

**Issue by Wjplatformer** [2KAbhishek/Posh2K#2]
### Description of the bug

It isn't? Posh2k? They look different. Is the theme different for powershell?

### Steps To Reproduce

1. Go through all the hard work to download oh-my-posh and posh2k ` onto powershell `
2. ![image](https://user-images.githubusercontent.com/82447031/205788635-07a14a4e-bb96-4424-8626-7f471ec72cef.png)
3. Wait a second moment

### Additional Information

Ok about this, this is what posh2k looks like on powershell <br>
![image](https://user-images.githubusercontent.com/82447031/205788762-625091bd-f7fa-4488-9c8a-fc1e0722d5cf.png)

And this is what it looks like on the docs
![image](https://user-images.githubusercontent.com/82447031/205788834-46038aee-9c86-4275-9415-1b9826e85059.png)
so I assume it's something to do with fonts. But I am not sure what `exactly` is the problem :skull:

**Comment by 2KAbhishek** [comment]
Thanks for the catch, there was a typo in commands, I have fixed it

**Comment by Wjplatformer** [comment]
wait now what

**Comment by Wjplatformer** [comment]
ehhhhh it still erm symbols stuff. I think it's due to the fact that I didn't install my fonts correctly. Ha, maybe this is a blessing in disguise. I may have done installation on my part incorrectly. So sorry, I think I have to read oh-my-posh docs again.
![image](https://user-images.githubusercontent.com/82447031/205890481-c58459ab-8bb4-4d8c-ae16-5dac140a2843.png)
****** I have already done my updates to the JSON file for powershell

**Comment by Wjplatformer** [comment]
![image](https://user-images.githubusercontent.com/82447031/205891902-2580e347-5851-4f42-87c7-a798d2a49cae.png)
I think it works, but it doesn't really look like what you erm have. Hmmmmmmmmmmmmmm, I think oh-my-posh does not recognize the Posh2K things
