### ISSUE TITLE
[BUG]: Is that more typo?

### ISSUE THREAD

**Issue by Wjplatformer** [2KAbhishek/Posh2K#3]
### Description of the bug

I still can't get posh2k into my terminal (oh-my-posh is working fine). There seems to be no JSON file, which seems to be the problem.

### Steps To Reproduce

1. If on Windows powershell, add what you are supposed to add to powershell
2. nothing changes

### Additional Information

![image](https://user-images.githubusercontent.com/82447031/206221282-88da3a78-954f-4674-8f65-ae00d8c0a068.png)
There's no JSON file
![image](https://user-images.githubusercontent.com/82447031/206221475-8bb69707-1d11-4192-bae0-94166973f6f2.png)
I also need clarification on HOW TO PUT THE PATH (liek an example path)

**Comment by 2KAbhishek** [comment]
Just link the posh2k.omp.json file, should work

**Comment by 2KAbhishek** [comment]
I have fixed the filenames on the doc, take a look

**Comment by Wjplatformer** [comment]
haha I tried that and it did (figured it myself offline), thanks! Posh2K looks great tho!
![image](https://user-images.githubusercontent.com/82447031/206453695-42fb7178-f1a8-43d0-8573-5ba4c74c1cd9.png)
